#!/bin/bash

# check we are in the right place
cwd=${PWD##*/}
if [ ${cwd} != "build.x86_64" ] ; then
    echo "[Must be executed in directory: build.x86_64]"
    echo "[You are in: ${cwd}]"
    exit
fi
# see if -h is present
if [ $# == 1 ] && [ $1 == "-h" ] ; then
    echo "Usage: ./mkall [-c -rc -s]"
    echo ""
    echo "FIRST TIME USE -- use:"
    echo "  -s     : standalone = -hw but no networking"
    echo ""
    echo "SUBSEQUENT USE:"
    echo "  no args: rebuild only whats changed"
    echo "  -c     : clean out object files and rebuild"
    echo "  -rc    : -c + CMake repository"
    exit
fi
# STANDALONE (full system without networking)
if [ $# == 1 ] && [ $1 == "-s" ] ; then
    echo "[STANDALONE: Cleaning files...]" 
    rm -rf ./CMakeFiles ./Makefile ./cmake_install.cmake 
    rm -rf ./CMakeCache.txt ./CTestTestfile.cmake 
    rm -rf ./sys ./usr ./usr.test.bin ./bin 
    rm -f ./lib/*.a ./lib/*.o 
    cp -f ../CMakeLists.txt.standalone ../CMakeLists.txt
    cp -f ../tools/fdisk/Makefile_standalone ../tools/fdisk/Makefile 
    cp -f ../sys/kernel/CMakeLists.txt.bear ../sys/kernel/CMakeLists.txt
    cmake ..
    make
    if [ $? -ne 0 ] ; then
	echo "[Compilation failed]";
	exit
    fi
    read -p "Install System? (y/n): " yn
    case ${yn} in
	[Yy]* )
	    ;;
	* )
	    echo "[Stopped]"; exit ;;
    esac
    # build the ram disk
    cd ../tools/fdisk
    sudo make newdisk
    # install the system in the PXE boot directory
    sudo cp bear_hdd /var/lib/tftpboot
    # blow away any old nfs mount points
    sudo service nfs-kernel-server stop
    sudo rm -f /var/lib/nfs/rmtab
    sudo service nfs-kernel-server start
    echo "[Check dhcp is running: ps -ale | grep dhcp3]"
    echo "[STANDALONE: Restart Dell Now]"
    exit
fi
# CLEAN 
if [ $# == 1 ] && [ $1 == "-c" ] ; then
    echo "[Cleaning files...]"
    rm -rf ./CMakeFiles ./Makefile ./cmake_install.cmake
    rm -rf ./CMakeCache.txt ./CTestTestfile.cmake
    rm -rf ./sys ./usr ./usr.test.bin ./bin
    rm -f ./lib/*.a ./lib/*.o
    # use existing ../CMakeLists file
    cmake ..
    make
    if [ $? -ne 0 ] ; then
	echo "[Compilation failed]";
	exit
    fi
    read -p "Install System? (y/n): " yn
    case ${yn} in
	[Yy]* )
	    ;;
	* )
	    echo "[Stopped]"; exit ;;
    esac
    # build the ram disk
    cd ../tools/fdisk
    sudo make newdisk
    # install the system in the PXE boot directory
    sudo cp bear_hdd /var/lib/tftpboot
    # blow away any old nfs mount points
    sudo service nfs-kernel-server stop
    sudo rm -f /var/lib/nfs/rmtab
    sudo service nfs-kernel-server start
    echo "[Check dhcp is running: ps -ale | grep dhcp3]"
    echo "[Restart Dell Now]"
    exit
fi
# REALCLEAN -- wipes everything away; if you 
# screwed up and made the system with sudo, do the following:
#   sudo mkall -rc
#   mkall -c
# This will wipe everything away and then rebuild as a normal
# user.
if [ $# == 1 ] && [ $1 == "-rc" ] ; then
    echo "[Cleaning ALL files and directories...]" ;
    rm -rf ./CMakeFiles ./Makefile ./cmake_install.cmake
    rm -rf ./CMakeCache.txt ./CTestTestfile.cmake
    rm -rf ./sys ./usr ./usr.test.bin ./bin
    rm -f ./lib/*.a ./lib/*.o
    # leave existing ../CMakeLists
    # make sure the loop0 device is available
    sudo losetup -d /dev/loop0
    sudo rm -rf ../tools/fdisk/partition
    # blow away any old nfs mount points
    sudo service nfs-kernel-server stop
    sudo rm -f /var/lib/nfs/rmtab
    sudo service nfs-kernel-server start
    exit
fi

# mkall -- go make the system and install it
make
if [ $? -ne 0 ] ; then
    echo "[Compilation failed]";
    exit
fi
# build the ram disk
cd ../tools/fdisk
sudo make newdisk
# install the system in the PXE boot directory
sudo cp bear_hdd /var/lib/tftpboot
# blow away any old nfs mount points
sudo service nfs-kernel-server stop
sudo rm -f /var/lib/nfs/rmtab
sudo service nfs-kernel-server start
echo "[Restart Dell Now]"
